name: OpeanAPI diff

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          path: head
      - name: Check out master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: base
      - name: Run OpenAPI Diff (from HEAD revision)
        id: run-diff
        uses: janinko/openapi-diff-action@v0.0.1
        with:
          head-spec: head/rest-api/pnc-openapi.yaml
          base-spec: base/rest-api/pnc-openapi.yaml
      - name: Test output
        run: echo "!!!!" ${{ steps.run-diff.outputs.diff-output }} "!!!!"
